---
version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "daily"
    cooldown:
      # Use prime numbers to stagger updates.
      default-days: 7
      semver-major-days: 29
      semver-minor-days: 11
      semver-patch-days: 5
    labels:
      - "ðŸ“¦ dependencies"
    assignees:
      - "kdeldycke"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      # Use prime numbers to stagger updates.
      default-days: 7
    labels:
      - "ðŸ“¦ dependencies"
    assignees:
      - "kdeldycke"